App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
]

App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'

urlpatterns = [
    path('', views.home, name='home'),
]

SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_name')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    facebook = models.URLField(blank=True)
    website = models.URLField(blank=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

App_Posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    caption = models.CharField(max_length=264)

    class Meta:
        ordering = ['-upload_date']

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_name')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = UserProfile
        fields = '__all__'

App_Posts/forms.py
from django import forms
from App_Posts.models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields=['image','caption']

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from App_Login.forms import CreateNewUser, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from App_Login.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_Posts.forms import PostForm


# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'title': 'Sign up. Instagram', 'form': form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Posts:home'))
    return render(request, 'App_Login/login.html', context={'title': 'Login', 'form': form})


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile.html', context={'form': form, 'title': 'Edit Profile'})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_Login/user.html', context={'title': 'Profile', 'form':form})

App_Posts/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def home(request):
    return render(request, 'App_Posts/home.html', context={'title':'Home'})

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>
    .sign_up{
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .log_in{
        width: 550px;
        border: 1px solid #ccc;
        padding: 25px;
    }
</style>
{% endblock %}
{% block body_block %}
    <center>
    <h3>Sign up to see photos.</h3>
    <div class="log_in">
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" style="width: 100%" class="btn btn-primary">Sign up</button>
        </form>
    </div>
    <div class="sign_in">
        <p>Don't have an account? <a href="{% url 'App_Login:sign_up' %}">Sign up</a></p>
    </div>
    </center>
{% endblock %}

templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>

</style>
{% endblock %}
{% block body_block %}
    <center>
    <div>
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" name="submit" style="width: 100%" class="btn btn-primary">Submit</button>
        </form>
    </div>
    </center>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>
    .sign_up{
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .log_in{
        width: 550px;
        border: 1px solid #ccc;
        padding: 25px;
    }
</style>
{% endblock %}
{% block body_block %}
    <center>
    <h3>Sign up to see photos.</h3>
    <div class="sign_up">
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" style="width: 100%" class="btn btn-primary">Sign up</button>
        </form>
    </div>
    <div class="log_in">
        <p>Have an account? <a href="#">Log in</a></p>
    </div>
    </center>
{% endblock %}

templates/App_Login/user.html
{% extends 'navbar.html' %}
{% block title_block %} {{ user.user_profile.full_name }} (@{{ user.username }}) {% endblock %}
{% block css_block %}
<style>
.crop{
    width: 200px;
    height: 200px;
    overflow: hidden;
}
.crop img{
    width: 400px;
    height: 300px;
    margin: -75px 0 0 -100px;
}
</style>
{% endblock %}
{% block body_block %}
    <div class="row">
        <div class="col-sm-4">
            {% if user.user_profile.profile_pic %}
        <img src="/media/{{ user.user_name.profile_pic }}" width="250px" height="250px">
        {% else %}
        <img src="/media/p.png" width="250px" height="250px" class="rounded-circle">
        {% endif %}
        </div>
    <div class="col-sm-8">
        <h3>{{ user.username }} &nbsp; <a class="btn btn-light" href="{% url 'App_Login:edit' %}">Edit Profile</a></h3>
        <br>
        <h5>{{ user.post.count }} Posts &nbsp; &nbsp; {{ user.follower.count }} Followers &nbsp; &nbsp; {{ user.following.count }} Followings</h5>
        <br>
        <h4>{{user.user_name.full_name}}</h4>
    </div>
    </div>
    <br>
    <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    New Post
</button>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Post a Photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Post</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
    <br>
    <br>
    <div class="row">
        {% for post in user.post.all %}
            <div class="crop">
            <img src="/media/{{ post.image }}" title="{{ post.caption }}">
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/App_Posts/home.html
{% extends 'navbar.html' %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>

</style>
{% endblock %}
{% block body_block %}
    <center>
    <div>
        <h1>Homepage</h1>
    </div>
    </center>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title_block %}Social{% endblock %}</title>
{% block css_block %}
{% endblock %}
</head>
<body>
<div class="container" style="padding-top: 20px">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title_block %}Social{% endblock %}</title>
{% block css_block %}
{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="navbar-brand" href="{% url 'App_Posts:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand" href="{% url 'App_Login:logout' %}">Logout</a>
      </li>
        {% if user.user_profile.profile_pic %}
        <li class="nav-item">
        <a class="navbar-brand" href="{% url 'App_Login:profile' %}"><img src="/media/{{ user.user_profile.profile_pic }}" width="25px" height="25px"></a>
      </li>
        {% else %}
        <li class="nav-item">
        <a class="navbar-brand" href="{% url 'App_Login:profile' %}"><img src="/media/p.png" width="25px" height="25px" class="rounded-circle"></a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
<div class="container" style="padding-top: 30px">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>